language: node_js

node_js:
  - "10.13.0"

cache:
  directories:
    - "node_modules"

before_install:
  - npm i -g yarn@1.10.1

script:
  - yarn test
  - yarn build

deploy:
  - provider: heroku
    api_key:
      secure: $HEROKU_API_SECURE
    app: $PACKAGE_NAME

notifications:
  slack:
    rooms:
        - '$SLACK_GROUP:$SLACK_TOKEN#development'
    on_success: change # default: always
    on_failure: always # default: always
