language: node_js

node_js:
  - "10.13.0"

cache: yarn

matrix:
  include:
    - name: Components Pipeline
      env: PACKAGE_NAME=pyxis-components

before_install:
  - npm i -g yarn@1.10.1

deploy:
  - provider: heroku
    api_key:
      secure: $HEROKU_API_SECURE
    app: $PACKAGE_NAME
