language: node_js

node_js:
  - "10.13.0"

cache: yarn

matrix:
  include:
    - name: Components Pipeline
      env: PACKAGE_PATH=packages/lib/components PACKAGE_NAME=pyxis-components

before_install:
  - npm i -g yarn@1.10.1

before_deploy:
  - cd $PACKAGE_PATH

# One stage runs after another
jobs:
  include:
    - stage: test
      script: yarn test
    - stage: build
      script: yarn build
    - stage: deploy

# Order of stages
stages:
  - test
  - build
  - deploy

deploy:
  - provider: heroku
    api_key:
      secure: $HEROKU_API_SECURE
    app: $PACKAGE_NAME
